# Site settings
title: U.S. Department of Labor Developer
email: neyman.neil.e@dol.gov
description: > # this means to ignore newlines until "baseurl:"
  Department of Labor Developer API Site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://developer.dol.dev:4000" # the base hostname & protocol for your site

# Build settings
markdown: rdiscount
permalink: pretty